version: 0.0
os: linux
files:
  - source: /
    destination: /opt/cubs/code/tmp/py-c3d
file_exists_behavior: OVERWRITE
permissions:
  - object: /opt/cubs/code/tmp/py-c3d
    pattern: "*"
    owner: ec2-user
    group: etl
    mode: 775
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 180
      runas: ec2-user
  AfterInstall:
    - location: after_install.sh
      timeout: 360
      runas: ec2-user
